-- SEED DATA FOR GYMS IN CHENNAI
-- Run this in the Supabase SQL Editor to populate the gyms table.

INSERT INTO gyms (name, city, state, country, latitude, longitude, address, phone, email, website, amenities, facilities, rating, review_count, is_verified, is_active, operating_hours_open, operating_hours_close)
VALUES
  (
    'Gold''s Gym Adyar', 
    'Chennai', 
    'Tamil Nadu', 
    'India', 
    13.0033, 
    80.2550, 
    'No 7, 1st Ave, Shastri Nagar, Adyar', 
    '+91 44 1234 5678', 
    'adyar@goldsgym.in', 
    'https://goldsgym.in', 
    ARRAY['Parking', 'Valet', 'Steam', 'Lockers'], 
    ARRAY['Cardio', 'Spinning Studio', 'Free Weights'], 
    4.4, 
    320, 
    TRUE, 
    TRUE, 
    '05:30:00', 
    '22:00:00'
  ),
  (
    'SLAM Lifestyle and Fitness Sholinganallur', 
    'Chennai', 
    'Tamil Nadu', 
    'India', 
    12.9010, 
    80.2279, 
    'Rajiv Gandhi Salai, Sholinganallur', 
    '+91 44 8765 4321', 
    'info@slamfitness.com', 
    'https://slamfitness.com', 
    ARRAY['WiFi', 'AC', 'Parking', 'Supplements Bar'], 
    ARRAY['CrossFit', 'Bodybuilding', 'Cardio'], 
    4.7, 
    510, 
    TRUE, 
    TRUE, 
    '05:00:00', 
    '23:00:00'
  ),
  (
    'Flux Fitness Studio Navalur', 
    'Chennai', 
    'Tamil Nadu', 
    'India', 
    12.8459, 
    80.2265, 
    'Rajiv Gandhi Salai (OMR), Egattur Village, Navalur', 
    '+91 44 9988 7766', 
    'navalur@fluxfitness.in', 
    'https://fluxfitness.in', 
    ARRAY['Showers', 'Changing Room', 'Personal Training'], 
    ARRAY['Functional Training', 'Zumba', 'Yoga'], 
    4.5, 
    180, 
    TRUE, 
    TRUE, 
    '06:00:00', 
    '21:30:00'
  ),
  (
    'Anytime Fitness Anna Nagar', 
    'Chennai', 
    'Tamil Nadu', 
    'India', 
    13.0850, 
    80.2100, 
    '2nd Avenue, Anna Nagar East', 
    '+91 81240 87777', 
    'annanagar@anytimefitness.in', 
    'https://anytimefitness.co.in', 
    ARRAY['24/7 Access', 'Private Showers', 'Security'], 
    ARRAY['Cardio', 'Strength', 'Functional Training'], 
    4.3, 
    250, 
    TRUE, 
    TRUE, 
    '00:00:00', 
    '23:59:59'
  ),
  (
    'O2 Health Studio Nungambakkam', 
    'Chennai', 
    'Tamil Nadu', 
    'India', 
    13.0600, 
    80.2400, 
    'Khader Nawaz Khan Rd, Nungambakkam', 
    '+91 44 4545 4545', 
    'contact@o2healthstudio.com', 
    'https://o2healthstudio.com', 
    ARRAY['Physiotherapy', 'Nutritionist', 'Cafe'], 
    ARRAY['Spinning', 'Aerobics', 'Gym Floor'], 
    4.6, 
    150, 
    TRUE, 
    TRUE, 
    '06:00:00', 
    '22:00:00'
  );
